"""
Mock adapter — always available, returns configurable deterministic scores.
Used in tests and local development where real API keys are not present.
"""
from typing import Optional

from app.adapters.base import ModelProviderAdapter


class MockAdapter(ModelProviderAdapter):
    """
    Deterministic mock adapter for testing and local development.

    Args:
        fixed_scores:  Optional mapping of criterion -> score.
        default_score: Fallback score for unspecified criteria (default 0.75).
    """

    def __init__(
        self,
        fixed_scores: Optional[dict[str, float]] = None,
        default_score: float = 0.75,
    ) -> None:
        self._fixed_scores: dict[str, float] = fixed_scores or {}
        self._default_score = max(0.0, min(1.0, default_score))

    @property
    def provider_name(self) -> str:
        return "mock"

    @property
    def default_model(self) -> str:
        return "mock-model-v1"

    @property
    def is_available(self) -> bool:
        return True

    async def complete(
        self,
        prompt: str,
        model: Optional[str] = None,
        **kwargs,
    ) -> str:
        return "Mock completion: generated by the mock adapter."

    async def score_quality(
        self,
        text: str,
        context: Optional[str],
        criteria: list[str],
        model: Optional[str] = None,
    ) -> tuple[dict[str, float], str]:
        scores = {c: self._fixed_scores.get(c, self._default_score) for c in criteria}
        reasoning = (
            f"Mock evaluation: {self._default_score} default "
            f"for {len(criteria)} criteria."
        )
        return scores, reasoning
